name: encapp
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  flutter_keyboard_visibility: ^5.0.3
  socket_io_client: ^1.0.1
  intl: ^0.17.0
  encrypt: ^5.0.0
  introduction_screen: ^2.1.0
  flutter_pw_validator: ^1.2.1
  settings_ui: ^1.0.0
  share: ^2.0.4
  toast: ^0.1.5
  qrscan: ^0.3.2
  flutter_dropdown: ^0.0.8
  group_radio_button: ^1.1.0
  provider: ^6.0.0
  shared_preferences: ^2.0.6
  device_info_plus: ^2.1.0
  http: ^0.13.3
  flutter_spinkit: ^5.0.0
  sqflite: ^2.0.0+3
  path_provider: ^2.0.2
  firebase_messaging: ^10.0.4
  flutter_local_notifications: ^5.0.0+4
  firebase_core: ^1.4.0
  flutter_isolate: ^2.0.0
  vibration: ^1.7.3
  one_context: ^1.1.0
  scrollable_positioned_list: ^0.1.10
  screen_state: ^2.0.0
  audioplayers: ^0.19.1
  volume_control: ^0.1.5
  image_picker: ^0.8.4
  dio: ^4.0.0
  path: ^1.8.0
  photo_view: ^0.12.0
  flutter_sound: ^8.3.10
  permission_handler: ^8.1.4+2
  media_info: ^0.8.0
  url_launcher: ^6.0.10
  open_file: ^3.2.1
  percent_indicator: ^3.0.1
  #agora_rtc_engine: ^4.0.6
  android_alarm_manager_plus: ^1.2.0
  star_menu: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/
    - assets/sounds/Boxing.mp3
    - assets/sounds/Carina.mp3
    - assets/sounds/GlassBreak.mp3
    - assets/sounds/Gong.mp3
    - assets/sounds/morse.mp3
    - assets/sounds/Parrot.mp3
    - assets/sounds/Prochitajte.mp3
    - assets/sounds/Whistle.mp3
    - assets/sounds/Note8.mp3
    - assets/sounds/D500.mp3
    - assets/sounds/Ding.mp3
    - assets/sounds/Ting.mp3
    - assets/sounds/Modern.mp3


  fonts:
    - family: UbuntuTitling
      fonts:
        - asset: fonts/UbuntuTitling-Bold.ttf

    - family: UbuntuTitle
      fonts:
        - asset: fonts/Ubuntu-Title.ttf